name: build-container

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
env:
  PORT: "10082"
  DOCKER_NAME: "macro-web"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_NAME }}:latest
      - name: Update docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}
            sudo docker stop ${{ env.DOCKER_NAME }}
            sudo docker rm ${{ env.DOCKER_NAME }}
            sudo docker run -dp ${{env.PORT}}:3000 --name ${{ env.DOCKER_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}
