name: Production

on:
  workflow_dispatch:
env:
  PORT: "10082"
  DOCKER_NAME: "macro-web"
jobs:
  Production:
    runs-on: ubuntu-latest
    steps:
      - name: Update docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}
            sudo docker stop ${{ env.DOCKER_NAME }}
            sudo docker rm ${{ env.DOCKER_NAME }}
            sudo docker run -dp ${{env.PORT}}:3000 --name ${{ env.DOCKER_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}
